MinigameCollection: test Class Reference
test Class Reference
#include <test.hpp>
Public Member Functions
test (SDL_Window *win, SDL_Renderer *renner, bool *running)
void run () override
Public Member Functions inherited from game
game (SDL_Window *win, SDL_Renderer *renner, bool *running)
Private Member Functions
void handleEvents () override
Additional Inherited Members
Protected Attributes inherited from game
SDL_Window * win
SDL_Renderer * renner
SDL_Event event
std::unordered_map< int, int > keys
bool * running
Detailed Description
Definition at line 10 of file test.hpp.
Constructor & Destructor Documentation
test()
test::test (SDL_Window * win, SDL_Renderer * renner, bool * running)
Definition at line 7 of file test.cpp.
                                                               : game(win,renner,running) {
 }
Member Function Documentation
run()
void test::run () override virtual
Implements game.
Definition at line 11 of file test.cpp.
References handleEvents(), game::renner, and game::running.
                {
     while(this->running){
         SDL_SetRenderDrawColor(this->renner, 0, 0, 0, 0);
         SDL_RenderClear(this->renner);
         this->handleEvents();
         SDL_RenderPresent(this->renner);\
         SDL_Delay(1);
     }
 }
handleEvents()
void test::handleEvents () override private virtual
Reimplemented from game.
Definition at line 23 of file test.cpp.
References game::handleEvents().
Referenced by run().
{
     game::handleEvents();
 }
The documentation for this class was generated from the following files:
Minigames/Testgame/test.hpp
Minigames/Testgame/test.cpp