MinigameCollection: main.cpp File Reference
main.cpp File Reference
#include "./core/header/definitions.hpp"
#include "menue/header/menue.hpp"
Functions
int filter (void *argumente, SDL_Event *event)
int main ()
Function Documentation
filter()
int filter (void * argumente, SDL_Event * event)
Definition at line 5 of file main.cpp.
Referenced by main().
{
     return (event->type != SDL_MULTIGESTURE &&
             event->type != SDL_DOLLARGESTURE && event->type != SDL_MULTIGESTURE &&
             event->type != SDL_FINGERMOTION && event->type != SDL_FINGERDOWN &&
             event->type != SDL_FINGERUP);
 }
main()
int main ()
Definition at line 12 of file main.cpp.
References menue::display(), and filter().
           {
     SDL_SetEventFilter(filter, nullptr);
     menue m;
     m.display();
 }